### ISSUE TITLE
Dependency: basefilter

### ISSUE THREAD

**Issue by vitoller** [andob/ROOM-Dynamic-Dao#4]
I believe the documentation is missing the dependency to basefilter
(in build.gradle)

When I do not add it, BaseFilter is not found

**Comment by andob** [comment]
I think you are right, something changed with how gradle works.
``:basefilter:`` was supposed to be an internal module, included inside ``:dyndao:`` module.
Will merge the two modules into one single module, ``:dyndao`` and will update the docs.
After the holidays.
Happy New Year!
